name: HTML Check

on:
  push:

# Example from https://github.com/Cyb3r-Jak3/html5validator-action/wiki/Getting-Started
jobs:
  linters: 
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/stylelint@master
        env:
          PATTERN: "*.css"
          INDENT_SPACES: 4
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Requried with all actions
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v7.1.1
      with:
        root: html/
