name: HTML & CSS Check

on:
  push:

# Example from https://github.com/Cyb3r-Jak3/html5validator-action/wiki/Getting-Started
jobs:
  html-css-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Required with all actions
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v7.1.1
      with:
        root: html/
    - name: Validates CSS
      uses: nok-ko/validate-css-action@main
      with:
        directory: public/css
